### ISSUE TITLE
Can it works with SSR?

### ISSUE THREAD

**Issue by sokyrko** [freearhey/vue2-filters#19]
I tried to use this package in my SSR-based Vue project, but it not works:

```
   ReferenceError: window is not defined
    at Object.<anonymous> (/www/node_modules/vue2-filters/dist/vue2-filters.js:625:5)
    at __webpack_require__ (/www/node_modules/vue2-filters/dist/vue2-filters.js:30:30)
    at ArrayProto (/www/node_modules/vue2-filters/dist/vue2-filters.js:74:18)
    at /www/node_modules/vue2-filters/dist/vue2-filters.js:77:10
    at webpackUniversalModuleDefinition (/www/node_modules/vue2-filters/dist/vue2-filters.js:3:20)
    at Object.<anonymous> (/www/node_modules/vue2-filters/dist/vue2-filters.js:10:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at r (/www/node_modules/vue-server-renderer/build.js:5817:16)
    at Object.<anonymous> (__vue_ssr_bundle__:30158:18)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
```
Error here because there is "if (window.Vue)" in code but window is undefined when code executes on server.

Thanks.

**Comment by arenddeboer** [comment]
If you modify src/index.js with the following and run npm run dev inside the module dir it will work:
```
import util from './util/index'
import * as stringFilters from './string/index'
import * as arrayFilters from './array/index'
import * as otherFilters from './other/index'
import Vue from 'vue'

const Vue2Filters = {
  install: function(Vue, options) {
    util.each(stringFilters, function(value, key) {
      Vue.filter(key, value)
    })

    util.each(otherFilters, function(value, key) {
      Vue.filter(key, value)
    })

    Vue.mixin({
      methods: {
        limitBy: arrayFilters.limitBy,
        filterBy: arrayFilters.filterBy,
        orderBy: arrayFilters.orderBy
      }
    })
  },
};

export default Vue2Filters;
export {
  Vue2Filters
};

// Automatic installation if Vue has been added to the global scope.
if (typeof window !== 'undefined' && window.Vue) {
  window.Vue.use(Vue2Filters);
}
```

**Comment by arenddeboer** [comment]
Better to not include:
```
import Vue from 'vue'
```
or it will be loaded twice it seams

**Comment by miladmeidanshahi** [comment]
Why this issue doesn't fixed yet ?!
